<?php

// Require
require_once 'ComposerRuntimeApi/autoload.php';
require_once 'Symfony/Bridge/Twig/autoload.php';
require_once 'Symfony/Component/Config/autoload.php';
require_once 'Symfony/Component/HttpFoundation/autoload.php';
require_once 'Symfony/Component/HttpKernel/autoload.php';
require_once 'Twig/autoload.php';

// Suggest

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___$classes[$cn];
        }
    },
    ___EXCEPTION___,
    ___PREPEND___
);
// @codeCoverageIgnoreEnd

// Files
